/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ReservationController;
import controller.RoomController;
import controller.TravelAgentController;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import model.Customer;
import model.Reservation;
import model.ReservationStatus;
import model.ReservationType;
import model.Room;
import model.RoomRate;
import model.RoomType;
import model.TravelAgent;

/**
 *
 * @author syarifuddin
 */
public class FormReservationView extends javax.swing.JFrame {

    /**
     * Creates new form FormReservation
     */
    int idReservation = 0;
    String namaCustomer = "";
    int nikCustomer = 0;
    int noTelpCustomer = 0;
    String alamatCustomer = "";
    String emailCustomer = "";
    String arrivalDate = "";
    String departureDate = "";
    int longStay = 0;
    int reservationStatus = 0;
    int reservationType = 0;
    int travelAgent = 0;
    int roomRate = 0;
    int roomType = 0;
    int roomNumber = 0;
    RoomController roomController;
    ReservationController reservationController;
    TravelAgentController agentController;

    public FormReservationView(Reservation res) throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        this.roomController = new RoomController();
        this.reservationController = new ReservationController();
        this.agentController = new TravelAgentController();
        this.getDataRoomRate();
        this.getDataReservatioStatus();
        this.getDataReservatioType();
        this.getDataTravelAgent();

        if (res != null) {
            tfNama.setText(res.getCustomer().getName());
            tfNik.setText(res.getCustomer().getNik());
            tfEmail.setText(res.getCustomer().getEmail());
            tfNoTelp.setText(res.getCustomer().getPhoneNumber());
            taAlamat.setText(res.getCustomer().getAddress());
            tfLongStay.setText(String.valueOf(res.getLongStay()));

            cbResStatus.getModel().setSelectedItem(res.getResStatus().getIdReservationStatus() + " - " + res.getResStatus().getNameReservationStatus());
            cbResType.getModel().setSelectedItem(res.getResType().getIdReseravationType() + " - " + res.getResType().getNameReservationType());
            if (res.getTravelAgent() > 0) {
                cbTravelAgent.getModel().setSelectedItem(res.getTravelagent().getIdTravelAgent() + " - " + res.getTravelagent().getNameTravelAgent());
            }
            cbRoomRate.getModel().setSelectedItem(res.getRoom().getRoomtype().getRoomrate().getIdRoomRate() + " - " + res.getRoom().getRoomtype().getRoomrate().getNameRoomRate());
            cbRoomType.getModel().setSelectedItem(res.getRoom().getRoomtype().getIdRoomType() + " - " + res.getRoom().getRoomtype().getNameRoomType());
            cbRoom.getModel().setSelectedItem(res.getRoom().getIdRoom() + " - " + res.getRoom().getRoomNumber());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNik = new javax.swing.JTextField();
        tfNoTelp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfArrivalDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfDepartureDate = new javax.swing.JTextField();
        tfLongStay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbRoomRate = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbRoomType = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbRoom = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        cbResStatus = new javax.swing.JComboBox<>();
        cbResType = new javax.swing.JComboBox<>();
        cbTravelAgent = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnCreateReservation = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Email");

        jLabel3.setText("Alamat");

        jLabel4.setText("NIK");

        jLabel5.setText("No Telp");

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel6.setText("CUSTOMER");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel7.setText("Reservation");

        jLabel8.setText("Arrival Date");

        jLabel9.setText("Departure Date");

        jLabel10.setText("Long Stay");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel11.setText("Room");

        jLabel12.setText("Room Rate");

        jLabel13.setText("Room Type");

        jLabel14.setText("Room");

        jLabel15.setText("Status");

        jLabel16.setText("Type");

        jLabel17.setText("Travel Agent");

        btnCreateReservation.setText("Create Reservation");
        btnCreateReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReservationActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(tfNama)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(262, 262, 262))
                        .addComponent(jLabel7)
                        .addComponent(jLabel11)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(127, 127, 127))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(cbRoomRate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbRoom, 0, 200, Short.MAX_VALUE))))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCreateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNik, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbResStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbResType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(cbTravelAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(tfDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(tfLongStay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLongStay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbResStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbResType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTravelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRoomRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnCreateReservation)
                    .addComponent(btnClose))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReservationActionPerformed
        try {
            namaCustomer = tfNama.getText();
            alamatCustomer = taAlamat.getText();
            nikCustomer = Integer.parseInt(tfNik.getText());
            emailCustomer = tfEmail.getText();
            noTelpCustomer = Integer.parseInt(tfNoTelp.getText());
            arrivalDate = tfArrivalDate.getText();
            departureDate = tfDepartureDate.getText();
            longStay = Integer.parseInt(tfLongStay.getText());

            Customer customer = new Customer();
            customer.setAddress(alamatCustomer);
            customer.setName(namaCustomer);
            customer.setNik(String.valueOf(nikCustomer));
            customer.setEmail(emailCustomer);
            customer.setPhoneNumber(String.valueOf(noTelpCustomer));
            Reservation res = new Reservation();
            res.setCustomer(customer);
            res.setArrivalDate(new SimpleDateFormat("dd-MM-yyyy").parse(arrivalDate));
            res.setDepartureDate(new SimpleDateFormat("dd-MM-yyyy").parse(departureDate));
            res.setLongStay(longStay);
            res.setReservationStatus(reservationStatus);
            res.setReservationType(reservationType);
            res.setTravelAgent(travelAgent);
            res.setIdRoom(roomNumber);
            this.reservationController.insertReservation(res);
        } catch (SQLException ex) {
            Logger.getLogger(FormReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FormReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCreateReservationActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        tfNama.setText("");
        tfEmail.setText("");
        tfNoTelp.setText("");
        tfNik.setText("");
        taAlamat.setText("");
        tfArrivalDate.setText("");
        tfDepartureDate.setText("");
        tfLongStay.setText("");
        cbResStatus.setSelectedIndex(0);
        cbResType.setSelectedIndex(0);
        cbTravelAgent.setSelectedIndex(0);
        cbRoomRate.setSelectedIndex(0);
        cbRoomType.removeAllItems();
        cbRoom.removeAllItems();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormReservationView(null).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormReservationView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void getDataReservatioStatus() {
        try {
            DefaultComboBoxModel dcbrs = new DefaultComboBoxModel();
            dcbrs.addElement("0 - Pilih Reservation Status ");
            for (ReservationStatus rs : this.reservationController.getDataReservationStatus(null)) {
                dcbrs.addElement(rs.getIdReservationStatus() + " - " + rs.getNameReservationStatus());
            }
            this.cbResStatus.removeAllItems();
            this.cbResStatus.setModel(dcbrs);

            this.cbResStatus.addItemListener((ItemEvent ie) -> {
                String item = cbResStatus.getSelectedItem().toString();
                reservationStatus = Integer.parseInt(item.substring(0, item.indexOf(" -")));
            });

        } catch (SQLException ex) {
            Logger.getLogger(FormReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getDataReservatioType() {
        try {
            DefaultComboBoxModel dcbrt = new DefaultComboBoxModel();
            dcbrt.addElement("0 - Pilih Reservation Type ");
            for (ReservationType rt : this.reservationController.getDataReservationType(null)) {
                dcbrt.addElement(rt.getIdReseravationType() + " - " + rt.getNameReservationType());
            }
            this.cbResType.removeAllItems();
            this.cbResType.setModel(dcbrt);

            this.cbResType.addItemListener((ItemEvent ie) -> {
                String item = cbResType.getSelectedItem().toString();
                reservationType = Integer.parseInt(item.substring(0, item.indexOf(" -")));
            });

        } catch (SQLException ex) {
            Logger.getLogger(FormReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getDataTravelAgent() {
        try {
            DefaultComboBoxModel dcbta = new DefaultComboBoxModel();
            dcbta.addElement("0 - Pilih Travel Agent ");
            for (TravelAgent ta : this.agentController.getDataTravelAgent(null)) {
                dcbta.addElement(ta.getIdTravelAgent() + " - " + ta.getNameTravelAgent());
            }
            this.cbTravelAgent.removeAllItems();
            this.cbTravelAgent.setModel(dcbta);

            this.cbTravelAgent.addItemListener((ItemEvent ie) -> {
                String item = cbTravelAgent.getSelectedItem().toString();
                travelAgent = Integer.parseInt(item.substring(0, item.indexOf(" -")));
            });

        } catch (SQLException ex) {
            Logger.getLogger(FormReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getDataRoomRate() throws SQLException {

        try {
            DefaultComboBoxModel dcbrr = new DefaultComboBoxModel();
            dcbrr.addElement("0 - Pilih Room Rate ");
            for (RoomRate rr : this.roomController.getDataRoomRate(null)) {
                dcbrr.addElement(rr.getIdRoomRate() + " - " + rr.getNameRoomRate());
            }
            this.cbRoomRate.removeAllItems();
            this.cbRoomRate.setModel(dcbrr);

            this.cbRoomRate.addItemListener((ItemEvent e) -> {

                try {
                    String item = cbRoomRate.getSelectedItem().toString();
                    int id = Integer.parseInt(item.substring(0, item.indexOf(" -")));
                    if (id > 0) {
                        roomRate = id;
                        DefaultComboBoxModel dcbrt = new DefaultComboBoxModel();
                        dcbrt.addElement("0 - Pilih Room Type ");

                        for (RoomType rt : this.roomController.getDataRoomTypeByRate(roomRate)) {
                            dcbrt.addElement(rt.getIdRoomType() + " - " + rt.getNameRoomType());
                        }

                        this.cbRoomType.removeAllItems();
                        this.cbRoomType.setModel(dcbrt);

                        this.cbRoomType.addItemListener(((ie) -> {
                            Object castText = ie.getItem();
                            String idType = castText.toString();
                            int idRoomType = Integer.parseInt(idType.substring(0, idType.indexOf(" -")));
                            if (idRoomType > 0) {
                                try {
                                    roomType = idRoomType;
                                    DefaultComboBoxModel dcbroom = new DefaultComboBoxModel();
                                    dcbroom.addElement("0 - Pilih Room ");
                                    for (Room room : this.roomController.getDataRoomByType(roomType)) {
                                        dcbroom.addElement(room.getIdRoom() + " - " + room.getRoomNumber());
                                    }
                                    this.cbRoom.removeAllItems();
                                    this.cbRoom.setModel(dcbroom);

                                    this.cbRoom.addItemListener((ItemEvent iev) -> {
                                        Object castTextRoom = iev.getItem();
                                        String idRoomTem = castTextRoom.toString();
                                        roomNumber = Integer.parseInt(idType.substring(0, idType.indexOf(" -")));
                                    });

                                } catch (SQLException ex) {
                                    Logger.getLogger(FormReservationView.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }

                        }));

                    } else {
                        roomRate = 0;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(RoomView.class.getName()).log(Level.SEVERE, null, ex);
                }
            });

        } catch (SQLException ex) {
            Logger.getLogger(RoomView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreateReservation;
    private javax.swing.JComboBox<String> cbResStatus;
    private javax.swing.JComboBox<String> cbResType;
    private javax.swing.JComboBox<String> cbRoom;
    private javax.swing.JComboBox<String> cbRoomRate;
    private javax.swing.JComboBox<String> cbRoomType;
    private javax.swing.JComboBox<String> cbTravelAgent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfArrivalDate;
    private javax.swing.JTextField tfDepartureDate;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLongStay;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNik;
    private javax.swing.JTextField tfNoTelp;
    // End of variables declaration//GEN-END:variables
}
